# Generated by Django 3.2.8 on 2021-10-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='korisničko ime')),
                ('password', models.CharField(max_length=1000, verbose_name='lozinka')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='datum pridruživanja')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='poslednji put ulogovan')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=20, verbose_name='ime')),
                ('last_name', models.CharField(max_length=20, verbose_name='prezime')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='broj telefona')),
            ],
            options={
                'verbose_name': 'User',
            },
        ),
    ]
