# Generated by Django 3.2.8 on 2021-10-23 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Doctor',
        ),
    ]
