# Generated by Django 3.2.8 on 2021-11-17 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211117_1015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
