# Generated by Django 3.2.8 on 2021-11-19 19:38

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_phone'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
