# Generated by Django 3.2.8 on 2021-11-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='form_title',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='left_block_text',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='left_block_title',
        ),
        migrations.AlterField(
            model_name='contact',
            name='email_address',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='factory_address',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Factory Address'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='office_address',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Office Address'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number_c',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Phone Number'),
        ),
    ]
