# Generated by Django 3.2.8 on 2021-11-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20211110_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='factory_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='office_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Office Address'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='phone',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
