# Generated by Django 3.2.8 on 2021-11-12 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20211110_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='factory_address',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='office_address',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='phone',
        ),
    ]
