# Generated by Django 3.2.8 on 2021-11-13 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20211112_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='field_classname',
            field=models.CharField(blank=True, max_length=254, verbose_name='Field classes'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='placeholder',
            field=models.CharField(blank=True, max_length=254, verbose_name='Placeholder'),
        ),
    ]
