# Generated by Django 3.2.8 on 2021-12-02 17:30

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('contact', '0006_auto_20211113_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='demo_content',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Service Description'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='demo_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Icon'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='demo_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Primary Image'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='demo_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
