# Generated by Django 3.2.8 on 2021-12-21 18:25

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_auto_20211216_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='contactus_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='description_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
