# Generated by Django 3.2.8 on 2021-12-21 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_auto_20211221_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactpage',
            old_name='contactus_text',
            new_name='contact_us_text',
        ),
    ]
