# Generated by Django 3.2.8 on 2021-12-21 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_rename_contactus_text_contactpage_contact_us_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='intro',
        ),
    ]
