# Generated by Django 3.2.8 on 2021-12-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0012_contactpage_contact_us_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='contact_us_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contact Us Text'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='contact_us_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
    ]
