# Generated by Django 3.2.8 on 2022-01-02 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('contact', '0013_auto_20211221_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Gallery'),
        ),
    ]
