# Generated by Django 3.2.8 on 2021-10-21 16:34

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner_title',
            field=wagtail.core.fields.RichTextField(blank=True, default='Hero Title', null=True, verbose_name='Hero Title'),
        ),
    ]
