# Generated by Django 3.2.8 on 2021-10-21 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='banner_title',
            new_name='banner_text',
        ),
    ]
