# Generated by Django 3.2.8 on 2021-10-21 18:24

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_banner_title_homepage_banner_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='secondary_text',
            field=wagtail.core.fields.RichTextField(blank=True, default='Hero Title', null=True, verbose_name='Hero Title'),
        ),
    ]
