# Generated by Django 3.2.8 on 2021-10-21 18:27

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0007_alter_homepage_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Hero Photo'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='secondary_text',
            field=wagtail.core.fields.RichTextField(blank=True, default='Hero Text', null=True, verbose_name='Hero Text'),
        ),
    ]
