# Generated by Django 3.2.8 on 2021-10-21 21:26

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20211021_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='banner_text',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Hero Title'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='secondary_text',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Hero Text'),
        ),
    ]
