# Generated by Django 3.2.8 on 2021-10-23 12:47

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0009_auto_20211021_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='bcontent_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Bottom Content Photo'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='bcontent_signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Signature Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='bcontent_text',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Bottom Content Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='bcontent_title',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Bottom Content Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='card_photo1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Card Photo 1'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='card_photo2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Card Photo 2'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='card_photo3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Card Photo 3'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='card_photo4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Card Photo 4'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content_p',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Content Secondary Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content_photo1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Content Photo1'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content_photo2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Content Photo2'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content_text',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Content Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content_text1',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='First Owl Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content_text2',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Second Owl Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content_text3',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Third Owl Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content_text4',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Fourth Owl Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content_title',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Content Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content_title1',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='First Owl Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content_title2',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Second Owl Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content_title3',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Third Owl Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content_title4',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Fourth Owl Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='embed_video',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Insert URL'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='first_card_text',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='First Card Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='first_card_title',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='First Card Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='founder_text',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Founder'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='fourth_card_text',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Fourth Card Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='fourth_card_title',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Fourth Card Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='owl_photo1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Owl Photo1'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='owl_photo2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Owl Photo2'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='owl_photo3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Owl Photo3'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='owl_photo4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Owl Photo4'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='owl_text',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Owl Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='owl_title',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Owl Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='quote_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Quote Photo'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='quote_text',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Qoute Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='quote_title',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Quote Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='res_list1',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Responsibilities List 1'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='res_list2',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Responsibilities List 2'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='res_list3',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Responsibilities List 3'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='res_list4',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Responsibilities List 4'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='res_list5',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Responsibilities List 5'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='res_list6',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Responsibilities List 6'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='second_card_text',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Second Card Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='second_card_title',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Second Card Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='skill1',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='First Skill'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='skill2',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Second Skill'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='skill3',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Third Skill'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='skill_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Skills Section Background  Photo'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='skill_title',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Skill Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='third_card_text',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Third Card Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='third_card_title',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Third Card Title'),
        ),
    ]
