# Generated by Django 3.2.8 on 2021-11-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20211112_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='slider_description1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Slider Description1'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='slider_description2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Slider Description2'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='slider_description3',
            field=models.CharField(blank=True, max_length=255, verbose_name='Slider Description3'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='slider_text1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Slider Text1'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='slider_text2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Slider Text1'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='slider_text3',
            field=models.CharField(blank=True, max_length=255, verbose_name='Slider Text1'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='slider_title1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Slider Tittle1'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='slider_title2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Slider Tittle1'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='slider_title3',
            field=models.CharField(blank=True, max_length=255, verbose_name='Slider Tittle1'),
        ),
    ]
