# Generated by Django 3.2.8 on 2021-11-12 13:05

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0012_auto_20211112_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='innovation_about',
            field=models.CharField(blank=True, max_length=255, verbose_name='Innovation About'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='innovation_description',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='innovation_highlight',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Hightlight Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='innovation_image1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image1'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='innovation_image2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image2'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='innovation_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Innovation Title'),
        ),
    ]
