# Generated by Django 3.2.8 on 2021-11-12 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_bookpagerelatedlinks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookPageRelatedLinks',
            new_name='ServiceBlockLinks',
        ),
    ]
