# Generated by Django 3.2.8 on 2021-11-12 14:13

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_bookpagerelatedlinks_serviceblocklinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceblocklinks',
            name='content',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Service Description'),
        ),
    ]
