# Generated by Django 3.2.8 on 2021-11-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_serviceblocklinks_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceblocklinks',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='serviceblocklinks',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
