# Generated by Django 3.2.8 on 2021-11-12 15:17

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0017_auto_20211112_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='feature_about',
            field=models.CharField(blank=True, max_length=255, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='feature_description',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='feature_highlight',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Hightlight Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='feature_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Feature Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='feature_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
    ]
