# Generated by Django 3.2.8 on 2021-11-12 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0018_auto_20211112_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='video_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Background Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='video_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='video_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
    ]
