# Generated by Django 3.2.8 on 2021-11-12 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0021_alter_homepage_video_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceblocklinks',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Icon'),
        ),
    ]
