# Generated by Django 3.2.8 on 2021-11-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20211112_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='trip_advisor',
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='google',
            field=models.URLField(blank=True, help_text='Your Google+ username', null=True),
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='linkedin',
            field=models.URLField(blank=True, help_text='Your Linkedin page URL', null=True),
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='twitter',
            field=models.URLField(blank=True, help_text='Your Twitter page URL', null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='facebook',
            field=models.URLField(blank=True, help_text='Your Facebook page URL', null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='youtube',
            field=models.URLField(blank=True, help_text='Your YouTube channel or user account URL', null=True),
        ),
    ]
