# Generated by Django 3.2.8 on 2021-11-12 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('home', '0025_auto_20211112_1801'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialMediaSettings',
            new_name='CompanySetting',
        ),
    ]
