# Generated by Django 3.2.8 on 2021-11-12 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('home', '0026_rename_socialmediasettings_companysetting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanySetting',
            new_name='CompanySettings',
        ),
    ]
