# Generated by Django 3.2.8 on 2021-11-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_rename_companysetting_companysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='working_hours',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
