# Generated by Django 3.2.8 on 2021-11-13 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('home', '0028_companysettings_working_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_title', models.CharField(blank=True, max_length=255, null=True)),
                ('footer_title', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook', models.URLField(blank=True, help_text='Your Facebook page URL', null=True)),
                ('google', models.URLField(blank=True, help_text='Your Google+ username', null=True)),
                ('twitter', models.URLField(blank=True, help_text='Your Twitter page URL', null=True)),
                ('linkedin', models.URLField(blank=True, help_text='Your Linkedin page URL', null=True)),
                ('youtube', models.URLField(blank=True, help_text='Your YouTube channel or user account URL', null=True)),
                ('office_address', models.CharField(blank=True, max_length=255, verbose_name='Office Address')),
                ('factory_address', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('working_hours', models.CharField(blank=True, max_length=255)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CompanySettings',
        ),
    ]
