# Generated by Django 3.2.8 on 2021-11-13 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20211113_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='copyright',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
