# Generated by Django 3.2.8 on 2021-11-16 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0030_generalsettings_copyright'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='slider_description1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='slider_description2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='slider_description3',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='slider_image1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='slider_image2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='slider_image3',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='slider_text1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='slider_text2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='slider_text3',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='slider_title1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='slider_title2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='slider_title3',
        ),
        migrations.AddField(
            model_name='homepage',
            name='primary_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Primary Image'),
        ),
    ]
