# Generated by Django 3.2.8 on 2021-11-26 15:43

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20211116_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='innovation_about',
            new_name='innovation_about1',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='innovation_highlight',
            new_name='innovation_highlight1',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='innovation_title',
            new_name='innovation_title1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='innovation_description',
        ),
        migrations.AddField(
            model_name='homepage',
            name='innovation_about2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Innovation About'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='innovation_highlight2',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Hightlight Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='innovation_title2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Innovation Title'),
        ),
    ]
