# Generated by Django 3.2.8 on 2021-11-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20211126_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='service_highlight_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Highlight Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
    ]
