# Generated by Django 3.2.8 on 2021-11-26 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_remove_homepage_service_highlight_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='feature_about',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='feature_description',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='feature_image',
        ),
    ]
