# Generated by Django 3.2.8 on 2021-11-26 18:03

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0035_auto_20211126_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureBlockLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('content', wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Service Description')),
                ('image_position', models.CharField(choices=[('RIGHT', 'Right'), ('LEFT', 'Left')], default='LEFT', max_length=5)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_block', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
