# Generated by Django 3.2.8 on 2021-11-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_auto_20211126_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='contact_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_highlight',
            field=models.CharField(blank=True, max_length=255, verbose_name='Highlight Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
    ]
