# Generated by Django 3.2.8 on 2021-12-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_auto_20211130_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='infographic_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
    ]
