# Generated by Django 3.2.8 on 2021-12-02 09:50

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('about', '0002_auto_20211021_2053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={},
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='banner_text',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='banner_title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='board_member_text1',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='board_member_text2',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='board_member_text3',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='board_member_text4',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='bot_content_photo',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='bot_content_text_dropdown1',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='bot_content_text_dropdown2',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='bot_content_text_dropdown3',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='bot_content_text_dropdown4',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='bot_content_title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='bot_content_title_dropdown1',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='bot_content_title_dropdown2',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='bot_content_title_dropdown3',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='bot_content_title_dropdown4',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='content_photo',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='content_text',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='content_title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='director_board_title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='first_board_member_photo',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='fourth_board_member_photo',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='mid_content_photo1',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='mid_content_photo2',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='mid_content_text1',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='mid_content_text2',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='mid_content_title1',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='mid_content_title2',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='page_text',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='page_title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='second_board_member_photo',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='third_board_member_photo',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='contact_description',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='contact_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Primary Image'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='contact_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='mission_about',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='mission_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='mission_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Mission & Goals Title'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='primary_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Primary Image'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='slider_description',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Slider Description'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='slider_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Slider Title'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='vision_description',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='vision_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Icon'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='vision_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Primary Image'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='vision_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
        migrations.CreateModel(
            name='GoalBlockLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Service Description')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Icon')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_block', to='about.aboutpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
