# Generated by Django 3.2.8 on 2021-12-22 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_aboutpage_mission_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='mission_icon',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='vision_icon',
        ),
    ]
