# Generated by Django 3.2.8 on 2021-10-22 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_menuitem_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='logo',
        ),
    ]
