# Generated by Django 3.2.8 on 2021-10-22 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('menus', '0003_remove_menuitem_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Top Content Photo'),
        ),
    ]
