# Generated by Django 3.2.8 on 2021-10-22 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('menus', '0004_menu_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='logo',
        ),
        migrations.AddField(
            model_name='menu',
            name='nav_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Nav Logo'),
        ),
    ]
