# Generated by Django 3.2.8 on 2021-10-22 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('menus', '0005_auto_20211022_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='link_page_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page'),
        ),
    ]
