# Generated by Django 3.2.8 on 2021-10-22 12:40

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailimages', '0023_add_choose_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('top_content_title', wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Top Content Title')),
                ('top_content_text', wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Top Content Text')),
                ('middle_content_title', wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Middle Content Title')),
                ('middle_content_text', wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Middle Content Text')),
                ('bottom_content_title', wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Bottom Content Title')),
                ('bottom_content_text', wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Bottom Content Text')),
                ('banner_text', wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Banner Text')),
                ('phone_number', wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Phone Number')),
                ('email_adress', wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Email Address')),
                ('bottom_content_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Bottom Content Photo')),
                ('middle_content_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Middle Content Photo')),
                ('top_content_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Top Content Photo')),
            ],
            options={
                'verbose_name': "Physician's Page",
            },
            bases=('wagtailcore.page',),
        ),
    ]
