# Generated by Django 3.2.8 on 2021-11-26 21:10

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('physician', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='physician',
            options={'verbose_name': 'physician'},
        ),
        migrations.RemoveField(
            model_name='physician',
            name='banner_text',
        ),
        migrations.RemoveField(
            model_name='physician',
            name='bottom_content_photo',
        ),
        migrations.RemoveField(
            model_name='physician',
            name='bottom_content_text',
        ),
        migrations.RemoveField(
            model_name='physician',
            name='bottom_content_title',
        ),
        migrations.RemoveField(
            model_name='physician',
            name='email_adress',
        ),
        migrations.RemoveField(
            model_name='physician',
            name='middle_content_photo',
        ),
        migrations.RemoveField(
            model_name='physician',
            name='middle_content_text',
        ),
        migrations.RemoveField(
            model_name='physician',
            name='middle_content_title',
        ),
        migrations.RemoveField(
            model_name='physician',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='physician',
            name='top_content_photo',
        ),
        migrations.RemoveField(
            model_name='physician',
            name='top_content_text',
        ),
        migrations.RemoveField(
            model_name='physician',
            name='top_content_title',
        ),
        migrations.AddField(
            model_name='physician',
            name='feature_highlight',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Hightlight Text'),
        ),
        migrations.AddField(
            model_name='physician',
            name='feature_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='physician',
            name='innovation_about1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Innovation About'),
        ),
        migrations.AddField(
            model_name='physician',
            name='innovation_highlight1',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Summary'),
        ),
        migrations.AddField(
            model_name='physician',
            name='innovation_image1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image1'),
        ),
        migrations.AddField(
            model_name='physician',
            name='innovation_title1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Innovation Title'),
        ),
        migrations.AddField(
            model_name='physician',
            name='primary_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Primary Image'),
        ),
        migrations.AddField(
            model_name='physician',
            name='service_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='physician',
            name='slider_description',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Slider Description'),
        ),
        migrations.AddField(
            model_name='physician',
            name='slider_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Slider Title'),
        ),
        migrations.AddField(
            model_name='physician',
            name='video_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Background Image'),
        ),
        migrations.AddField(
            model_name='physician',
            name='video_title',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Video Title'),
        ),
        migrations.AddField(
            model_name='physician',
            name='video_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Video URL'),
        ),
        migrations.CreateModel(
            name='ServiceBlockLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Service Description')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Icon')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_block', to='physician.physician')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeatureBlockLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('content', wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Feature Description')),
                ('image_position', models.CharField(choices=[('RIGHT', 'Right'), ('LEFT', 'Left')], default='LEFT', max_length=5)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_block', to='physician.physician')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceGalleryBlockLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Icon')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='devicegallery_block', to='physician.physician')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
