# Generated by Django 3.2.8 on 2021-11-26 21:14

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('physician', '0002_auto_20211126_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physician',
            name='innovation_about1',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Details'),
        ),
    ]
