# Generated by Django 3.2.8 on 2021-11-26 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('physician', '0003_alter_physician_innovation_about1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='physician',
            old_name='innovation_about1',
            new_name='innovation_about',
        ),
        migrations.RenameField(
            model_name='physician',
            old_name='innovation_highlight1',
            new_name='innovation_highlight',
        ),
        migrations.RenameField(
            model_name='physician',
            old_name='innovation_image1',
            new_name='innovation_image',
        ),
        migrations.RenameField(
            model_name='physician',
            old_name='innovation_title1',
            new_name='innovation_title',
        ),
    ]
