# Generated by Django 3.2.8 on 2021-11-26 21:36

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('physician', '0004_auto_20211126_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physician',
            name='feature_highlight',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Highlight Text'),
        ),
        migrations.AlterField(
            model_name='physician',
            name='innovation_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image'),
        ),
    ]
