# Generated by Django 3.2.8 on 2021-11-26 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('physician', '0005_auto_20211126_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicegalleryblocklinks',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Gallery'),
        ),
    ]
