# Generated by Django 3.2.8 on 2021-11-30 22:00

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('physician', '0007_rename_service_title_physician_gallery_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementBlockLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Description')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Gallery')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='physician',
            name='video_image',
        ),
        migrations.RemoveField(
            model_name='physician',
            name='video_title',
        ),
        migrations.RemoveField(
            model_name='physician',
            name='video_url',
        ),
        migrations.AddField(
            model_name='physician',
            name='management_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Icon'),
        ),
        migrations.DeleteModel(
            name='ServiceBlockLinks',
        ),
        migrations.AddField(
            model_name='managementblocklinks',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_block', to='physician.physician'),
        ),
    ]
