# Generated by Django 3.2.8 on 2021-11-30 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('physician', '0009_alter_physician_management_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physician',
            name='management_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Icon'),
        ),
    ]
