# Generated by Django 3.2.8 on 2021-11-30 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physician', '0010_alter_physician_management_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementblocklinks',
            name='image_position',
            field=models.CharField(choices=[('RIGHT', 'Right'), ('LEFT', 'Left')], default='LEFT', max_length=5),
        ),
    ]
