# Generated by Django 3.2.8 on 2021-12-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physician', '0014_physician_feature_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='physician',
            name='infographic_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
    ]
