# Generated by Django 3.2.8 on 2021-12-16 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('physician', '0015_physician_infographic_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicegalleryblocklinks',
            name='device1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Device1'),
        ),
        migrations.AddField(
            model_name='devicegalleryblocklinks',
            name='device2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Device2'),
        ),
        migrations.AddField(
            model_name='devicegalleryblocklinks',
            name='device3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Device3'),
        ),
        migrations.AddField(
            model_name='devicegalleryblocklinks',
            name='device4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Device4'),
        ),
        migrations.AddField(
            model_name='devicegalleryblocklinks',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
