# Generated by Django 3.2.8 on 2021-12-16 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('physician', '0016_auto_20211216_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureblocklinks',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='physician',
            name='feature_gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Gallery'),
        ),
    ]
