# Generated by Django 3.2.8 on 2022-01-02 12:38

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('physician', '0017_auto_20211216_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicegalleryblocklinks',
            name='device1',
        ),
        migrations.RemoveField(
            model_name='devicegalleryblocklinks',
            name='device2',
        ),
        migrations.RemoveField(
            model_name='devicegalleryblocklinks',
            name='device3',
        ),
        migrations.RemoveField(
            model_name='devicegalleryblocklinks',
            name='device4',
        ),
        migrations.AddField(
            model_name='physician',
            name='devices_description',
            field=wagtail.core.fields.RichTextField(blank=True, default='', null=True, verbose_name='Highlight Text'),
        ),
    ]
