# Generated by Django 3.2.8 on 2022-02-10 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('physician', '0018_auto_20220102_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='physician',
            name='infographic_gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Gallery'),
        ),
    ]
